Repository CS157A-Team-31/Smart-Group-Financial, pull requests merged in 2019-11, with the labels that each got.

#32 User Authentication
  .gitignore
  server/App.js
  server/auth/passport.js
  server/controller/event.controller.js
  server/controller/user.controller.js
  server/package.json
Labels: feature, good first issue, implementing

#34 Update Router
  client/src/App.js
  client/src/RouterComponent.js
  client/src/actions/getUserIdentity.js
  client/src/actions/register/registerApiCall.js
  client/src/actions/setUserTokenAction.js
  client/src/components/Landing.js
  client/src/components/Navbar.js
  client/src/components/auth/Register.js
  client/src/constant.js
  client/src/index.js
  client/src/page/Landing.js
  client/src/page/LandingPage.js
  client/src/page/NavBar.js
  client/src/page/RegisterPage.js
  client/src/reducers/userReducers.js
  client/src/route/RouterCompnent.js
  client/src/route/RoutesComponent.js
  client/src/serviceWorker.js
  client/src/store.js
  client/src/utils.js
  server/controller/user.controller.js
Labels: enhancement

#33 Ui login
  client/src/RouterComponent.js
  client/src/actions/login/attemptLoginAction.js
  client/src/actions/login/loginApiCall.js
  client/src/components/Landing.js
  client/src/components/auth/Login.js
  client/src/constant.js
  client/src/page/GroupPage.js
  client/src/page/Landing.js
  client/src/page/LoginPage.js
  client/src/reducers/userReducers.js
  client/src/route/RoutesComponent.js
Labels: feature

#35 Added Group Page Queries
  .gitignore
  server/controller/party.controller.js
Labels: enhancement

#24 very basic homepage setup
  client/package.json
  client/src/App.js
  client/src/actions/createEvent/attemptCreateEvent.js
  client/src/actions/createGroup/attemptCreateGroup.js
  client/src/components/auth/HomePage.js
  client/src/components/auth/Register.js
  client/src/components/headerComponent/CustomNavbar.js
  client/src/page/CreateGroupPage.js
  client/src/page/HomePage.js
  client/src/page/Landing.js
  client/src/page/LoginPage.js
  client/src/page/RegisterPage.js
  client/src/reducers/userReducers.js
  client/src/route/RoutesComponent.js
  package.json
  server/controller/user.controller.js
Labels: good first issue, implementing
